# Generated by Django 4.2 on 2023-06-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('password', models.CharField(max_length=40, verbose_name='Password')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
